# Use the official Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy only the necessary files to optimize caching
COPY requirements.txt .
COPY app.py /app/
COPY /models/encoder_model.h5 /app/
COPY /models/decoder_model.h5 /app/
COPY /dataset/indonesian.txt /app/
COPY /dataset/english.txt /app/
COPY /pickle/input_tokenizer.txt /app/
COPY /pickle/output_tokenizer.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files into the container
COPY . .

# Expose the port FastAPI will run on
EXPOSE 8000

# Command to run the FastAPI app using Uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
